# Script to "make" the aggregated files for deployment

# Open the merged output file. We overwrite whatever is currently there.
File.open('levelup.js', 'w') do |mergedJsFile|

  # Auto-generated warning
  mergedJsFile << "////////////////////////////////////////////////////////////////////////////////\n"
  mergedJsFile << "// This file was automatically generated from files in the `js` directory.    //\n"
  mergedJsFile << "// Do not edit this file by hand. Run `ruby make.rb` to regenerate it.        //\n"
  mergedJsFile << "////////////////////////////////////////////////////////////////////////////////\n"

  # Gather all of the Javascript files.
  jsDir = File.absolute_path('js')
  jsFiles = Dir["#{jsDir}/*.js"]

  # Iterate over the JavaScript files and merge them into the main file.
  jsFiles.each do |file|

    # Friendly status update
    puts File.basename(file)

    # Add header
    mergedJsFile << "\n\n////////////////////////////////////////\n"
    mergedJsFile << "// #{File.basename(file).center(34)} //\n"
    mergedJsFile << "////////////////////////////////////////\n\n"

    # Append line by line
    source = File.open(file, 'r').read
    source.each_line do |line|
      mergedJsFile << line
    end
  end
end